export const SECONDS_IN_MINUTE = 60;
export const SECONDS_IN_HOUR = SECONDS_IN_MINUTE * 60;
export const SECONDS_IN_DAY = SECONDS_IN_HOUR * 24;
export const MILLISECONDS_IN_SECONDS = 1000;

export const DEFAULT_PORT = 3000;
